/* Generated By:JJTree&JavaCC: Do not edit this line. XConstants.java */

/** 
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface XConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int APARENTESES = 5;
  /** RegularExpression Id. */
  int FPARENTESES = 6;
  /** RegularExpression Id. */
  int ACOLCHETES = 7;
  /** RegularExpression Id. */
  int FCOLCHETES = 8;
  /** RegularExpression Id. */
  int ACHAVES = 9;
  /** RegularExpression Id. */
  int FCHAVES = 10;
  /** RegularExpression Id. */
  int PONTOVIRGULA = 11;
  /** RegularExpression Id. */
  int VIRGULA = 12;
  /** RegularExpression Id. */
  int INT = 13;
  /** RegularExpression Id. */
  int CHAR = 14;
  /** RegularExpression Id. */
  int VOID = 15;
  /** RegularExpression Id. */
  int IF = 16;
  /** RegularExpression Id. */
  int ELSE = 17;
  /** RegularExpression Id. */
  int WHILE = 18;
  /** RegularExpression Id. */
  int FOR = 19;
  /** RegularExpression Id. */
  int RETURN = 20;
  /** RegularExpression Id. */
  int SOMA = 21;
  /** RegularExpression Id. */
  int SUBTRACAO = 22;
  /** RegularExpression Id. */
  int MULTIPLICACAO = 23;
  /** RegularExpression Id. */
  int DIVISAO = 24;
  /** RegularExpression Id. */
  int ATRIBUICAO = 25;
  /** RegularExpression Id. */
  int IGUALDADE = 26;
  /** RegularExpression Id. */
  int MAIOR = 27;
  /** RegularExpression Id. */
  int MENOR = 28;
  /** RegularExpression Id. */
  int MAIORIGUAL = 29;
  /** RegularExpression Id. */
  int MENORIGUAL = 30;
  /** RegularExpression Id. */
  int DIFERENTE = 31;
  /** RegularExpression Id. */
  int AND = 32;
  /** RegularExpression Id. */
  int OR = 33;
  /** RegularExpression Id. */
  int NOT = 34;
  /** RegularExpression Id. */
  int NUM = 35;
  /** RegularExpression Id. */
  int ID = 36;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"(\"",
    "\")\"",
    "\"[\"",
    "\"]\"",
    "\"{\"",
    "\"}\"",
    "\";\"",
    "\",\"",
    "\"int\"",
    "\"char\"",
    "\"void\"",
    "\"if\"",
    "\"else\"",
    "\"while\"",
    "\"for\"",
    "\"return\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"=\"",
    "\"==\"",
    "\">\"",
    "\"<\"",
    "\">=\"",
    "\"<=\"",
    "\"!=\"",
    "\"&&\"",
    "\"||\"",
    "\"!\"",
    "<NUM>",
    "<ID>",
  };

}
