/* Generated By:JavaCC: Do not edit this line. XTreeConstants.java Version 4.1d1 */
public interface XTreeConstants
{
  public int JJTSTART = 0;
  public int JJTX = 1;
  public int JJTCOM = 2;
  public int JJTCOMES = 3;
  public int JJTIF = 4;
  public int JJTELSE = 5;
  public int JJTRET = 6;
  public int JJTOP = 7;
  public int JJTOPVAR = 8;
  public int JJTSOP = 9;
  public int JJTNOT = 10;
  public int JJTVARPLUS = 11;
  public int JJTVAR = 12;
  public int JJTVARTYPE = 13;
  public int JJTLOOP = 14;
  public int JJTPV = 15;


  public String[] jjtNodeName = {
    "Start",
    "X",
    "COM",
    "COMES",
    "IF",
    "ELSE",
    "RET",
    "OP",
    "OPVAR",
    "SOP",
    "NOT",
    "VARPLUS",
    "VAR",
    "VARTYPE",
    "LOOP",
    "PV",
  };
}
/* JavaCC - OriginalChecksum=4d6ab2e65f1069069a54c53e8418d6dd (do not edit this line) */
